theme:
  name: "hoy"
  type: "agency_theme"
  sidebars:
    'locations#show' : 'properties_results_sidebar'
    'properties#index' : 'properties_results_sidebar'
    'properties#show' : 'properties_show_sidebar'
    'branches#show' : 'branches_show_sidebar'
    'branches#index' : 'our_offices_sidebar'
    'pages#show' : 'cms_page_sidebar'
    'home#home' : 'homepage_sidebar'
    'staff#show' : 'staff_show_sidebar'
    'articles#show' : 'cms_page_sidebar'
    'articles#index' : 'cms_page_sidebar'